### ISSUE TITLE
Add support for BGP authentication

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/calicoctl#1076]
Feature request from @awlx (AKA **Sail0r** on IRC).  Wants to limit access to their RR based on BGP password.

If we did implement this, it probably wouldn't be a good idea to store it in etcd.  Maybe a config file mounted into the container or an env variable?

**Comment by robbrockbank** [comment]
I assume this is request is asking us to support peers that have authentication turned on rather than having authentication on our BGP node.  If that is the case, it might be a little tricky to just handle with a config file or env variable as you'd need authentication info on a per-peer basis.

@fasaxc What's the issue with having this in etcd?  I assume if you do have in etcd then you'd probably want to ensure your etcd transport is encrypted.

**Comment by fasaxc** [comment]
Well, it just needs more thought.  No good having a password on your BGP session if all the passwords are stored in etcd and your etcd is accessible from any node.

**Comment by awlx** [comment]
Actually a cluster-wide setting will be ok. I just don't want any dev to announce it's own things out of a container. When the RR runs a peering group.

**Comment by fasaxc** [comment]
@robbrockbank I don't think I'm a good person to track this but I know you've worked on BGP config recently, is this something that makes sense to add?

**Comment by robbrockbank** [comment]
I think it does make sense, and it seems to be something Bird supports - the key thing is translating that into a sensible configuration model (environments or stored in etcd) and then updating our Bird templates accordingly.

**Comment by teran-mckinney** [comment]
This is needed for using floating IPs on Vultr. Is there a workaround for this?

**Comment by lwr20** [comment]
As a workaround, you could customise your own calico BGP templates (stored in the calico-node docker image) to have a password since BIRD actually supports this.

**Comment by fasaxc** [comment]
Fixed in https://github.com/projectcalico/confd/pull/360
