### ISSUE TITLE
How to run calico when public IP is not visible inside hosts (on some cloud providers)?

### ISSUE THREAD

**Issue by ThomasLohner** [projectcalico/calicoctl#1113]
Hi,

i'm running calico across multiple cloud providers. Basically there are two kinds of IP implementations out there:

1) Public IP is "visible" inside VM (i.e. Digital Ocean)

```
host1# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 04:01:56:2b:c2:01 brd ff:ff:ff:ff:ff:ff
    inet 46.101.208.xxx/18 brd 46.101.255.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet 10.19.0.10/16 scope global eth0
       valid_lft forever preferred_lft forever
```

2) Only private IP is "visible" inside VM (i.e. AWS, OpenStack, Hetzner...)

```
host2# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc pfifo_fast state UP group default qlen 1000
    link/ether fa:16:3e:bb:4a:94 brd ff:ff:ff:ff:ff:ff
    inet 172.16.0.4/24 brd 172.16.0.255 scope global eth0
       valid_lft forever preferred_lft forever

host3# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc pfifo_fast state UP group default qlen 1000
    link/ether fa:16:3e:89:c9:54 brd ff:ff:ff:ff:ff:ff
    inet 172.16.0.3/24 brd 172.16.0.255 scope global eth0
       valid_lft forever preferred_lft forever
```

In this case the cloud provider connects a public IP from outside of the vm with whatever magic they may use.

If i run `calicotl node --libnetwork` the network won't work because obviously private IPs are not routed between the three hosts. So on **host2** and **host3** i've started calico with `calicoctl node --libnetwork --ip=<PUBLIC-IP>`
### The good

Calico network is working, containers across all hosts can ping each other.
### The bad

It's **very slow** between **host2** and **host3**, they can't connect to each other so i guess traffic is routed through **host1**? Honestly i didn't expect this to work at all which is suprisingly good somehow. It's very bad on the other hand that hosts can't use their direct link when they are basically sitting next to each other and instead traffic is routed "around the world".

**Host1** (public IP visible in VM) can connect to all calico nodes:

```
host1# calicoctl status
calico-node container is running. Status: Up 2 days
Running felix version 1.4.0

IPv4 BGP status
IP: 46.101.208.xxx    AS Number: 64511 (inherited)
+-----------------------------------------+-------------------+-------+------------+-------------+
|   Peer address                          |     Peer type     | State |   Since    |     Info    |
+-----------------------------------------+-------------------+-------+------------+-------------+
|  185.56.xxx.51 (**public IP of Host2**) | node-to-node mesh |   up  |  20:23:09  | Established |
|  185.56.xxx.52 (**public IP of Host3**) | node-to-node mesh |   up  |  20:23:09  | Established |
+-----------------------------------------+-------------------+-------+------------+-------------+
```

**Host2** and **Host3** can connect to **Host1** but not to each other:

```
host3# calicoctl status
calico-node container is running. Status: Up 16 hours
Running felix version 1.4.0

IPv4 BGP status
IP: 185.56.xxx.52    AS Number: 64511 (inherited)
+-----------------+-------------------+-------+----------+-----------------------------------------+
|   Peer address  |     Peer type     | State |  Since   |                   Info                  |
+-----------------+-------------------+-------+----------+-----------------------------------------+
|  46.101.208.xxx | node-to-node mesh |   up  | 20:23:09 |               Established               ||    172.16.0.4   | node-to-node mesh | start | 12:33:49 | Active        Socket: Connection closed |
|    185.56.xxx.51   | node-to-node mesh | start | 12:33:49 | Active        Socket: Connection closed |+-----------------+-------------------+-------+----------+-----------------------------------------+
```
### Questions

Is there any way to make this work so all hosts can connect to each other and traffic doesn't need to be routed through third parties? Is this related to #819? Would it be possible to add something like `--bind-ip` or `--advertise-ip`?

**Comment by robbrockbank** [comment]
Hi @ThomasLohner - in the last two `calicoctl status` outputs, Host 1 is connecting to two 185.56.* addresses.

How come the output from Host 2 (3?) is connecting to host 1 and the private address of Host 3 (2?) - are these outputs from different test scenarios?

**Comment by liljenstolpe** [comment]
Hi @ThomasLohner, some questions, if you don't mind.

1) What public cloud are host2 and host3 running in?  What is the environment (i.e. if AWS, are they in the same VPC)?
2) Can you ping between host2 and host3?  If so, can you do a traceroute and see if there is something between host2 and host3?
3) If you ssh from host2 to host3, can you see what IP address host3 sees the inbound ssh coming from?

**Comment by ThomasLohner** [comment]
@robbrockbank Yes, you're right. I mixed up two test scenarios while writing this issue. The output was when i did not use --ip on host2 and host3. I've corrected the output above so it shows the current situation. sorry.

**Comment by ThomasLohner** [comment]
@liljenstolpe 

> 1) What public cloud are host2 and host3 running in? What is the environment (i.e. if AWS, are they in the same VPC)?

It's an OpenStack Implementation at SysEleven, but i can reproduce this with every cloud provider where public ("floating") IPs are not assigned inside the vm.

> 2) Can you ping between host2 and host3? If so, can you do a traceroute and see if there is something between host2 and host3?

```
host2#  traceroute 172.16.0.3
traceroute to 172.16.0.3 (172.16.0.3), 30 hops max, 60 byte packets
 1  172.16.0.3 (172.16.0.3)  3.254 ms  3.258 ms  3.133 ms
```

> 3) If you ssh from host2 to host3, can you see what IP address host3 sees the inbound ssh coming from?

```
host2# ssh 172.16.0.3
Welcome to Ubuntu 16.04.1 LTS (GNU/Linux 4.4.0-34-generic x86_64)
Last login: Wed Aug 17 21:40:29 2016 from 172.16.0.4
```

Internal traffic between the vms host2 and host3 happens on 172.16.0.0/24. Only external Traffic (like to host1) gets NATed to 185.56.xxx.51 / 185.56.xxx.52:

```
host2# curl ip.syseleven.de
185.56.xxx.51
```

I think the problem is that bird can't bind to the IP i've provided with `--ip=` because this IP does not exist on the host, just like #819. On the other hand i can't use the internal IPs because then host1 wouldn't be able to see either of them --> Dead End :-/

**Comment by liljenstolpe** [comment]
@ThomasLohner, we haven't forgotten you.  We're looking at this and will get back to you as soon as possible.

**Comment by SirEdvin** [comment]
As I understand, now it's impossible.
I can configure bird to bind to one address and publish another, but felix ignore this and always use public address.

**Comment by ThomasLohner** [comment]
@SirEdvin Can you explain how? I don't see options for this in `calicoctl node --help`

**Comment by fvigotti** [comment]
Hi, 
I'm having the same issue with hetzner vps ( also scaleway and other providers have this kind of "nat" of public ip )
in a 3 node cluster  ( on hetzner vps ) : 

+---------------+-------------------+-------+----------+-----------------------------------------+
|  Peer address |     Peer type     | State |  Since   |                   Info                  |
+---------------+-------------------+-------+----------+-----------------------------------------+
| --hidden----- | node-to-node mesh | start | 17:01:18 | Active        Socket: Connection closed |
| --hidden----- | node-to-node mesh | start | 17:01:18 | Active        Socket: Connection closed |
+---------------+-------------------+-------+----------+-----------------------------------------+

have you found a solution ?
I've tried with both -ipip and  --nat-outgoing and also with just  "--nat-outgoing"

thank you,
Francesco

**Comment by SirEdvin** [comment]
@ThomasLohner I edit bird.cfg file and change route to external ip addresses.

**Comment by ThomasLohner** [comment]
Any news on this? I'd really love to span calico network over multiple cloud providers...

**Comment by ThomasLohner** [comment]
Guys, i'm still struggling with this issue. Do you see any chance to make this possible or can you suggest a workaround? The goal is to spread calico network over multiple cloud providers.

**Comment by tmjd** [comment]
@matthewdupre or @liljenstolpe is there any update on this?

**Comment by kprabhak** [comment]
@ThomasLohner Only just recently saw this issue. Have you considered running a route reflector outside of Calico (with a public IP, so calico nodes can reach it), so (using your original example) host2 and host3 are able to see routes to each other via their respective public IP's (or whatever openstack floating ip/magic natted ip gets assigned by the provider)?
Obviously, you'll want to give some thought to network design to ensure that within an individual cloud provider you're preferring the local private addresses instead of the public addresses.

**Comment by ThomasLohner** [comment]
@kprabhak I'm open to any suggestions ;-) We also need `--ipip` and `--nat-otigoing`. So if i understand correctly, i'd start calico-node on host2 and host3 listening on their private IPs and the route reflector would announce those private IPs to be accessible through their public counterparts? With this configuration Traffic would still use the direct link because public IPs are simply natted to the private IPs. Would make perfect sense. Only i'm not sure how to configure a route reflector to do that. Any hints on where to start? And while i'm thinking about that... couldn't i just set a route on host1 to reach private IPs of host2 and host3 through their public IPs? Why didn't i think about that? Or would this break `--ipip` and `--nat-outgoing`?

**Comment by kprabhak** [comment]
Will avoid comment on adding static routes on routers, given the potential pitfalls with accidental routing loops ;)
Will share some notes on route reflector configuration in a few minutes.

**Comment by kprabhak** [comment]
Here's some notes (copying from my notes from an install I'd done a while ago) using the calico/bird route reflector (although you could use any route reflector, including just a standalone bird instance).

### 1. Deploy RR:
`docker run --privileged --net=host -d -e IP=<RR_IP> -e ETCD_AUTHORITY=<etcd:2379> -e ETCD_ENDPOINTS=https://etcd1:2379,https://etcd2:2379,https://etcd3:2379 -v /home/core/certs:/etc/ssl/certs -e ETCD_SCHEME=https -e ETCD_CA_CERT_FILE=<ca-cert> -e ETCD_CERT_FILE=<etcd-server-cert> -e ETCD_KEY_FILE=<etcd-server-key> calico/routereflector:latest`

### 2. (If you have more than 1 RR) Add RR info into etcd so RR's can full mesh amongst each other:
curl --cacert <ca-cert> --cert <etcd-server-cert> --key <etcd-server-key> -L https://etcd-ip:2379/v2/keys/calico/bgp/v1/rr_v4/RR_IP -XPUT -d value="{\"ip\":\"RR_IP\",\"cluster_id\":\"172.24.0.1\"}"
(you can use an arbitrary bgp cluster id, but it needs to be the same within the cluster).

Verify that the RR's have found each other, and have formed a full mesh (docker exec *rr-container-id* cat /config/bird.cfg)

### 3. Create RR-peer.yaml & have nodes peer w/ RR(s):

```
apiVersion: v1
kind: bgpPeer
metadata:
  scope: node
  node: node-IP
  peerIP: RR-IP
spec:
  asNumber: 65555

```
(create additional yaml's if you have more than 1 RR)

### 4.  Have nodes peer with RR(s) and turn off full mesh globally.

```
calicoctl create -f ./peer-RR.yaml
calicoctl node status
calicoctl config set nodeToNodeMesh off

```

Would need to give some additional thought to configuration in your design to ensure that nodes within a single provider use private IP's instead of public IP's.

**Comment by tmjd** [comment]
Does anyone object to closing this issue?

**Comment by scm-ns** [comment]
So, its not clear to me. If the public ip is not visible within the net interfaces on a machine, calico will not work ? Is there no config where I can set calico to use public ip when it tries to reach out to the other nodes, and when it is trying to bind to the interface on a machine, it uses the private ip ?

**Comment by manelio** [comment]
i know this was closed, but I’m facing the same situation.

I don’t understand why there’s no a clear information about such a common scenario: nodes with no visible public ip, nodes behind a home router, ...

I was searching for weeks without success.

If I found a working solution I’ll write a step by step guide about the right approach to the problem.

I’m sure it will be matter of adding some routes or create a few iptables rules, but I lack some networking knowledge.

**Comment by ehsanrocket** [comment]
I have faced this issue . 
how can I solve that ?

**Comment by loxal** [comment]
@liljenstolpe @ThomasLohner 
Is this issue related to https://github.com/hetznercloud/hcloud-cloud-controller-manager/issues/40? I have an issue on Hetzner where I need to provide my a specific entry under `externalIPs`. No doing so leaves me with a `<pending>` external IP entry.
