### ISSUE TITLE
Bird fails startup if /var/run/calico not volume mounted

### ISSUE THREAD

**Issue by djosborne** [projectcalico/calicoctl#1123]
I'm using `docker run calico/node` to start node (instead of using `calicoctl`). I accidentally did not volume mount in `/var/run/calico` from the host, which means that `/var/run/calico` doesn't exist in the container. As a result, bird repeatedly fails with `2016-08-19_21:06:16.72566 bird: Cannot create control socket /var/run/calico/bird.ctl: No such file or directory`.

This was not a very intuitive problem to diagnose. We should make this more user friendly. I'll suggest two possible fixes:
1. create an empty `/var/run/calico` during the Docker build no matter what, so bird won't fail startup.
2. Add checks during startup.py to better handle if `/var/run/calico` does not exist.

**Comment by caseydavenport** [comment]
The question is, do we want to allow people to run `calico/node` without mounting in the `/var/run/calico` directory?

At the moment, this is only used for `bird.ctl`, which is only mounted to the host so that `calicoctl` can access BIRD.

On the one hand, if you don't plan on using `calicoctl` then it means you shouldn't need to mount in the directory.  However, it feels like it could be a big source of confusion if we let it start up and then calicoctl commands start failing.

I'm not sure what my preference is - I think it is slightly towards error-ing out if the directory isn't mounted in, but I'm not too fussed either way.

**Comment by matthewdupre** [comment]
I'd probably go the other way and just `mkdir -p` the directory in the container, so it doesn't fail.

A log (maybe info/warning) if the directory isn't mounted would be OK, but I don't think it's worth failing to start.  I don't love making calico-node "worse", because calicoctl doesn't give very good error messages.

**Comment by caseydavenport** [comment]
This should be fast and easy and is something I'd like to do to clean up our self-hosted k8s manifest.
