### ISSUE TITLE
--ipip vs --nat-outgoing

### ISSUE THREAD

**Issue by MikeSpreitzer** [projectcalico/calicoctl#1296]
(1) I am told that currently `--ipip` only works in conjunction with `--nat-outgoing` --- for pod to host connections.  Make sure this is clearly documented, I did not know it.

(2) I would like pod-to-host connections to work with `--ipip` and not `--nat-outgoing`.

**Comment by matthewdupre** [comment]
More details: the observed problem was that a container was unable to connect to a remote host when running `--ipip`, but worked with `--ipip --nat-outgoing` or neither option (the test environment didn't actually require ipip).

**Comment by matthewdupre** [comment]
Some general thoughts on the interactions between the two features:

If IPIP is required, then all inter-host traffic where either end is a pod needs to be tunnelled in both directions.  Otherwise most environments where overlays are needed will drop the traffic.
- This always worked when both ends are pods.
- Host (running Calico) to pod was fixed (with some caveats*) in https://github.com/projectcalico/calico-containers/pull/721.  This works by adding an address from a Calico pool to the `tunl0` device, which will generally be picked when opening a socket
- Pod to host (running Calico) is usually covered by `--nat-outgoing`; since it's traffic from a pod to somewhere outside the Calico pools.
- Pod to host (not running Calico) can only be solved by `--nat-outgoing` (or adding Calico) if the environment requires IPIP.
- For completeness: host (not running Calico) to pod can only be done using a load balancer / proxy if the environment requires IPIP.

(*: It doesn't work if the source address is overridden on the originating host.)

**Comment by matthewdupre** [comment]
Some specific thoughts on this particular issue (pod to host), as observed in the test environment that didn't need IPIP, set up with `--ipip` only:

- The outgoing packets will be sent un-tunnelled (since that's a routing decision, which only depends on the destination).
- If the destination host is RPF checking on eth1, then it will drop the packets.
- The return traffic would be tunnelled.
- It would then probably be dropped by the RPF check on caliX.

In an environment where IPIP was actually needed, the outgoing packets would be dropped by the fabric anyway.

There are a few ways to fix / work around this (assuming IPIP is needed).
- Use `--nat-outgoing`.
- Connect to the address of tunl0 on the receiving host instead of eth1.
- Adjust the routing with `--ipip`, using multiple routing tables and ip rules to do source routing (essentially); using tunl0 for all traffic where the source or destination is a Calico pod.

@MikeSpreitzer you mentioned wanting IPIP but not nat-outgoing, but I don't think I asked why at the time?  I'm not sure exactly what the use case is.

**Comment by heschlie** [comment]
cc @lxpollitt

**Comment by MikeSpreitzer** [comment]
I'm afraid I do not remember the use case.  I do not have a need for `ipip` without `nat-outgoing` at this time.

**Comment by matthewdupre** [comment]
Here's a use-case from fxposter on Slack: running Kubernetes and host endpoints in AWS.
- The pods need to be tunnelled, but it's undesirable to use nat-outgoing to the host endpoints, because then they can't properly enforce policy.

**Comment by tmjd** [comment]
> (1) I am told that currently --ipip only works in conjunction with --nat-outgoing --- for pod to host connections. Make sure this is clearly documented, I did not know it.

Fixed by https://github.com/projectcalico/calico/issues/592

> (2) I would like pod-to-host connections to work with --ipip and not --nat-outgoing.

Tracked by https://github.com/projectcalico/calicoctl/issues/1562

I'm closing this issue since it is covered by the above.
