### ISSUE TITLE
Ability to delete selections of workload endpoints and other resources.

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calicoctl#1383]
I'd like to remove _all_ workload endpoints for a given node / orchestrator combination without 

```
calico $calicoctl delete wep --node=mynode --orchestrator=k8s
Failed to delete 'workloadEndpoint' resource: insufficient identifiers, missing 'workload'
```

**Comment by caseydavenport** [comment]
Would be cool to be able to perform operations on weps based on label selectors too, but not part of this issue :)

**Comment by caseydavenport** [comment]
Marking this as high priority since it hinders ability to clean up etcd.

**Comment by robbrockbank** [comment]
@caseydavenport What does k8s do here when there are multiple identifiers?

I'm nervous about a missing identifier simply meaning "wildcard" because it'll be too easy to accidentally delete a bunch of config....   But perhaps a "*" or similar identifier to explicitly indicate "wildcard", or add another CLI parm such as "--wildcard-missing-parms"  or "--delete-multiple" or something along those lines.

What's your take?

**Comment by caseydavenport** [comment]
An equivalent would be k8s namespaces, where you need to declare it or specify "all".

e.g

```
kubectl delete pods -l foo=bar
```

vs

```
kubectl delete pods -l foo=bar -n kube-system
```

vs 

```
kubectl delete pods -l foo=bar --all-namespaces
```


So, maybe we need 

```
--all-nodes
--all-orchestrators
...
```

**Comment by caseydavenport** [comment]
Noting that this would be useful for ALL resource types - not just WEPs.
