### ISSUE TITLE
Is drop the correct DefaultEndpointToHostAction for Kubernetes?

### ISSUE THREAD

**Issue by matthewdupre** [projectcalico/calicoctl#1389]
From calico-users Slack:
```
angel [3:26 AM]  
@matt_dupre Thanks again at pointing me at `DefaultEndpointToHostAction` - all working great now, `DROP` seems an odd default for running on  kubernetes.
```
@caseydavenport - should we change it?  We already vary this by orchestrator (e.g. OpenStack VMs all connect to the host for DHCP/metadata).

**Comment by caseydavenport** [comment]
Seems sensible enough to change.

Does seem like a number of apps desire connectivity to the container host.

**Comment by caseydavenport** [comment]
One of the symptoms here is that pods scheduled on the master (or, for example, a single node kubeadm cluster) can't talk to the apiserver.

This will cause Pods like kubedns or the dashboard to fail.

The fix for this is to add the following environment variable to the calico-node Pod in calico.yaml

```
- name: FELIX_DEFAULTENDPOINTTOHOSTACTION
   value: ACCEPT
```

**Comment by gunjan5** [comment]
So this only seems to affect etcdless mode. Not exactly sure why but everytime I've hit this it was with etcdless. etcd mode works every time without having to set this

**Comment by caseydavenport** [comment]
Fixed https://github.com/projectcalico/calico/pull/464
