### ISSUE TITLE
how to make calico advertise static routes?

### ISSUE THREAD

**Issue by ruansteve** [projectcalico/calicoctl#1432]
I met this use case: 
My k8s network use calilo and I want to run a IPSec VPN pod to connect to a remote network. Topo is like this:
remote network(10.1.0.0/16)  ---------------->  | VPN Pod (172.16.3.3)  in K8s node 1| 
.............................................................................................. |  Pod (172.16.5.3) in           k8s node 2| 

As I can image, I can add a static route in k8s node1:
10.1.0.0/16 nexthop 172.16.3.3 
then this route will be advertise by bird to K8s node2:
But in fact, it's not. 
What should I can configure to make bird advertise static route?

Thanks.

**Comment by caseydavenport** [comment]
@ruansteve by default Calico configures BIRD such that it only advertises routes for addresses within its configured pools (see [here](https://github.com/projectcalico/calicoctl/blob/2d59018cb550464f98b9582ea0a42c6932e7a84b/calico_node/filesystem/etc/calico/confd/templates/bird_ipam.cfg.template#L6))

However, you should be able to configure custom filters in etcd which will be interpreted by this template: https://github.com/projectcalico/calicoctl/blob/master/calico_node/filesystem/etc/calico/confd/templates/custom_filters.cfg.template 

An alternative might be to just add a Calico IPPool for `10.1.0.0/16`, but you'll have to make sure it is disabled for IPAM so that Calico doesn't assign Pod addresses from that range.

**Comment by ruansteve** [comment]
Thanks. I will try it.
