### ISSUE TITLE
How to change the IP range for a block

### ISSUE THREAD

**Issue by shouhong** [projectcalico/calicoctl#1434]
Currently the default IP block range is /26 like below. Is there any way to change this? Such as change it to /24. So more IPs are available to be assigned. Thanks!
```
root@ubuntu-24:~# etcdctl ls --recursive /calico | grep ipv4/block
/calico/ipam/v2/assignment/ipv4/block/192.168.161.0-26
/calico/ipam/v2/assignment/ipv4/block/192.168.204.128-26
/calico/ipam/v2/assignment/ipv4/block/192.168.92.64-26
/calico/ipam/v2/host/ubuntu-24/ipv4/block/192.168.161.0-26
/calico/ipam/v2/host/ubuntu-25/ipv4/block/192.168.204.128-26
/calico/ipam/v2/host/ubuntu-26/ipv4/block/192.168.92.64-26
```

**Comment by caseydavenport** [comment]
@shouhong Currently there is no way to change the size of the blocks used by Calico IPAM.  However, this doesn't actually limit you to a /26 per host because Calico can assign multiple /26s to each host.

For each host, when it runs out of addresses in the block(s) assigned to it, it will assign a new /26 block to that host, so you can assign as many addresses as you like.

**Comment by shouhong** [comment]
Thanks a lot, the information is very helpful!
