### ISSUE TITLE
Calico for ARM?

### ISSUE THREAD

**Issue by xied75** [projectcalico/calicoctl#1475]
Dear all,

I was following kubeadm instructions here: https://kubernetes.io/docs/getting-started-guides/kubeadm/
and Calico is one of the options for network as here: https://kubernetes.io/docs/admin/addons/

Then following the link http://docs.projectcalico.org/v2.0/getting-started/kubernetes/installation/hosted/kubeadm/ I can see the contents of this file:
http://docs.projectcalico.org/v2.0/getting-started/kubernetes/installation/hosted/kubeadm/calico.yaml

Within this yaml file there are 5 docker images to download:
1, gcr.io/google_containers/etcd:2.2.1
2, quay.io/calico/node:v1.0.1
3, calico/cni:v1.5.5
4, calico/kube-policy-controller:v0.5.2
5, calico/ctl:v1.0.1

No. 1 can be easily replaced with gcr.io/google_containers/etcd-arm. But the other four doesn't seem to have versions compiled for ARM. From my understanding anything code in Go shouldn't be difficult to compile to ARM (I might be wrong), is there any plan to get these components working for ARM?

Best regards,

Dong

**Comment by tomdee** [comment]
It's something we'd like to add support for but have no immediate plans for.

**Comment by tomdee** [comment]
The kube policy controller is still written in Python so that one might be tricky. We also ship a bird binary in the node image, which is written in C.

**Comment by caseydavenport** [comment]
xref: https://github.com/projectcalico/cni-plugin/issues/364

**Comment by michaelc0n** [comment]
having the ability run/test calico on RaspberryPi (ARM) would be awesome.

**Comment by vielmetti** [comment]
one issue with building the `bird` dependency on arm64 might be this report of an old config.guess file:

http://bird.network.cz/pipermail/bird-users/2016-December/010817.html

I'm also interested in seeing Calico for arm64.

**Comment by deitch** [comment]
@vielmetti see https://github.com/projectcalico/bird/pull/52

Got `bird` working on arm, and, yes, required updating `config.guess` and `config.sub`.

**Comment by boyracer2014** [comment]
Is there any ETA for Calico on ARM/ARM64 ?

**Comment by deitch** [comment]
Ive been working on it for a while. Got PRs through for bird and go-build, almost for felix. Once that’s in, a few more components. I’m just helping from the outside though.

**Comment by jsrz** [comment]
+1 on Arm support.

I was able to built all the Calico components and deploy on a K8S cluster.  Some basic things to watch out for (not a comprehensive list, just some things I encountered):

-Alpine:3.4 was being used as a base image for many of the Docker images. This needs to get bumped up to 3.6 to support Arm.
- Various make files and build scripts need to be updated to check for under laying Arch so the right commands can be called during the build. For example, so that CALICO_BUILD can be set when building calico/node (among other things).
- Some of the Docker images were installing the package glibc-bin, which is not available in the apk repos for Arm. I removed that, and things were fine. Makes we wonder if this should be removed altogether for all architectures?
- Binaries are getting pulled in from some CNCF projects (container networking). These binaries are hard coded to x86. The container networking project does have Arm binaries (and I think PPC as well) in their releases. Thus, it's easy to point to the right binary to pull in. No need to build binaries for projects external to Calico. :)
- I recall there being a few minor mistakes in the overall build instructions.

For the go-build image, I wonder if the "-arm64" suffix should not be added when that image is build. It would allow us to get away without setting CALICO_BUILD.

These are things I would like to contribute, but at this moment, I don't believe I have the bandwidth, so I figure I should post some of what I encountered, in case anyone wants to contribute.

**Comment by deitch** [comment]
@jsrz the initial PR for `calico/felix` was merged, enables explicit cross-building of binary and docker image. New PR is open to automate full cross-build and cross-image with multi-arch manifest.

Initial (similar) PR is open for `calico/typha`. 

Once those are in, we will do the same multi-arch work for typha, then move to the other components. Major constraint now, I believe, is the time from the core team. 

> For example, so that CALICO_BUILD can be set when building calico/node

That one will be last.

> Some of the Docker images were installing the package glibc-bin, which is not available in the apk repos for Arm

There was a PR that did that for `go-build`, I think, and more coming.

> Binaries are getting pulled in from some CNCF projects (container networking). These binaries are hard coded to x86

Is that in `calico/node`? I haven't gotten to work on that one yet. It will be last.

Open some PRs?

**Comment by jsrz** [comment]
Nice to hear things are moving forward. I have to say, my comments above are likely stale as I got all this working maybe some 2-3 months ago (release 2.5 if I recall correctly). With respect to the CNCF binaries getting pulled in during build, it was the **calico/cni** image.

I just took a quick peak at the latest source (https://github.com/projectcalico/cni-plugin/blob/master/Makefile).  Looks like it has already been updated, so nevermind that. I was building release 2.5 at the time (I think), it looks like the changes got in at release 3.0.

I'd have to go through the process again to be able to compile a list of what issues I encounter.

**Comment by deitch** [comment]
We have been doing al to of work on this. @mkumatag opened two issue to track the multi-architecture builds and manifests. See https://github.com/projectcalico/calico/issues/1865 and https://github.com/projectcalico/calico/issues/1866

They are not fully up to date yet, but should be soon. So far we have 4 components on multiple archs, 1 with an open PR, and more to come. Single image tag with multi-arch manifests is following and in process.

**Comment by caseydavenport** [comment]
Closing this in favor of projectcalico/calico#1865 and projectcalico/calico#1866 for tracking multi-arch.
