### ISSUE TITLE
Allow configurable interface matching for first-found auto detection.

### ISSUE THREAD

**Issue by robbrockbank** [projectcalico/calicoctl#1555]
Based on user experience.

**Comment by caseydavenport** [comment]
@robbrockbank rather than continue to add more options here, why don't we support letting users pass in the interface regexes they want to skip / match?

I'm worried that we're going to keep adding these and it's going to break someone who is relying on us finding a, for example, "vtep" interface.  Also worried that it's not scalable for us to change the code every time someone else has another interface they want to ignore..

**Comment by robbrockbank** [comment]
Yup I'm for that too :-)

**Comment by caseydavenport** [comment]
Has this been fixed by https://github.com/projectcalico/calico/pull/885 and https://github.com/projectcalico/calicoctl/pull/1675?

**Comment by mgleung** [comment]
Yup!  I'll add the release notes
