### ISSUE TITLE
quay master builds still showing v1.1.0-xxx

### ISSUE THREAD

**Issue by ozdanborne** [projectcalico/calicoctl#1608]
calicoctl 1.1.1 has been out for awhile but our quay.io master builds are being tagged as v1.1.0-xxxxx.
- https://quay.io/repository/calico/ctl?tab=tags
- https://quay.io/repository/calico/node?tab=tags

Not only should we bump this to 1.1.1,  RELEASING.md should get updated with instructions on how to do it.

**Comment by tomdee** [comment]
They're tagged with v1.1.0-xxxx because v1.1.0 was tagged from master as per our process. v1.1.1 wasn't tagged from master but I'm getting pretty confused looking at it. I think we probably have a problem with releases that get tagged from the the vx.y.z-series branches which I'm not immediately sure about how we fix, maybe merging them to master.

But @djosborne I'm pretty confused about what you did to release v1.1.1 - I _think_ you probably did the wrong thing, so once we understand what you did, let's document the _right_ process better.

**Comment by caseydavenport** [comment]
Looks like we're getting properly tagged images now - @tomdee @ozdanborne can we close this issue?
