### ISSUE TITLE
containers within the same network can not connect with each other

### ISSUE THREAD

**Issue by qiankunli** [projectcalico/calicoctl#1817]
there are 3 vm create by virtualbox

ubuntu ： 16.04
docker version：18.01.0-ce
calicoctl version:  1.6.3
quay.io/calico/node:   v2.6.2

ip pool:
```
apiVersion: v1
kind: ipPool
metadata:
cidr: 172.32.0.0/16
spec:
ipip:
enabled: true
nat-outgoing: true
disabled: false
````

docker network : 
`docker network create --driver calico --ipam-driver  calico-ipam --subnet=172.32.0.0/16 net1`

profile 
```
{
"kind": "profile",
"apiVersion": "v1",
"metadata": {
"name": "net1",
"tags": [
"net1"
]
},
"spec": {
"ingress": [
{
  "action": "allow",
  "source": {
    "tag": "net1"
  },
  "destination": {}
},
{
  "action": "allow",
  "source": {
    "nets": ["192.168.56.0/24"]
  },
  "destination": {}
}
],
"egress": [
{
  "action": "allow",
  "source": {},
  "destination": {}
}
]
}
```

run container:
`docker run -it --net="net1" busybox sh`

container 
```
cali0     Link encap:Ethernet  HWaddr EE:AA:66:53:32:86
          inet addr:172.32.185.73  Bcast:172.32.185.73  Mask:255.255.255.255
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:3 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:338 (338.0 B)  TX bytes:0 (0.0 B)
```

mac address of cali0 is not ee:ee:ee:ee:ee:ee

**Comment by qiankunli** [comment]
if i execute `ifconfig cali0 hw ether ee:ee:ee:ee:ee:ee`, everything is ok. now the question is that calico can not set the mac address of cali0 "ee:ee:ee:ee:ee:ee" ,why?

**Comment by tmjd** [comment]
Are you setting the mac address of the interface in the container or the host side of the container?
What prompted you to set it to that value?  Did you see an error somewhere that Calico was trying to set it and was unable to?

**Comment by xiaolei0125** [comment]
@qiankunli @tmjd  Do you solved this problem ? 
I met the same problem， my environment is:
ubuntu： 16.04.1
docker version：18.03.0-ce
calicoctl version: 1.6.3
quay.io/calico/node: v2.6.5
    The container cali0 mac is not "ee:ee:ee:ee:ee:ee", but in host, use cmd "arp -a", found the veth is " ee:ee:ee:ee:ee:ee",  which cause container network cannot receivie packets from host

**Comment by brat002** [comment]
The same.

**Comment by CharlieR-o-o-t** [comment]
Same problem: 
Mac address not updated, seems that due to docker 18.03. 

Docker 18.03
Calico node v2.6.5

Arp table from hostmachine:
`arp -a | grep 192.168.215.132
? (192.168.215.132) at ee:ee:ee:ee:ee:ee [ether] PERM on cali474957106ec`

Ifconfig from hostmachine:
`ifconfig cali474957106ec
cali474957106ec: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::c0a5:82ff:fe9e:15a3  prefixlen 64  scopeid 0x20<link>
        ether c2:a5:82:9e:15:a3  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0`
So, veth device created and exists. 


Some diagnostic from log:
Felix:
`Apr 26 08:13:26 hostname calico-felix[20127]: 2018-04-26 08:13:26.161 [INFO][20127] int_dataplane.go 574: Received *proto.WorkloadEndpointUpdate update from calculation graph msg=id:<orchestrator_id:"libnetwork" workload_id:"libnetwork" endpoint_id:"474957106ec3d6cffa3c0e4163595ded57dbbdb1144a67b97056e0065a82178d" > endpoint:<state:"active" name:"cali474957106ec" mac:"ee:ee:ee:ee:ee:ee" profile_ids:"net1" ipv4_nets:"192.168.215.132/32" >
Apr 26 08:13:26 hostname calico-felix[20127]: 2018-04-26 08:13:26.162 [INFO][20127] route_table.go 558: Failed to access interface because it doesn't exist. error=Link not found ifaceName="cali474957106ec" ipVersion=0x4
Apr 26 08:13:26 hostname calico-felix[20127]: 2018-04-26 08:13:26.162 [INFO][20127] route_table.go 404: Failed to get interface; it's down/gone. error=Link not found ifaceName="cali474957106ec" ipVersion=0x4
Apr 26 08:13:26 hostname calico-felix[20127]: 2018-04-26 08:13:26.162 [INFO][20127] route_table.go 293: Interface missing, will retry if it appears. ifaceName="cali474957106ec" ipVersion=0x4
Apr 26 08:13:26 hostname calico-felix[20127]: 2018-04-26 08:13:26.162 [INFO][20127] table.go 438: Loading current iptables state and checking it is correct. ipVersion=0x4 table="filter"
Apr 26 08:13:26 hostname calico-felix[20127]: 2018-04-26 08:13:26.169 [INFO][20127] status_combiner.go 78: Endpoint down for at least one IP version id=proto.WorkloadEndpointID{OrchestratorId:"libnetwork", WorkloadId:"libnetwork", EndpointId:"474957106ec3d6cffa3c0e4163595ded57dbbdb1144a67b97056e0065a82178d"} ipVersion=0x4 status="down"
Apr 26 08:13:26 hostname calico-felix[20127]: 2018-04-26 08:13:26.169 [INFO][20127] status_combiner.go 98: Reporting combined status. id=proto.WorkloadEndpointID{OrchestratorId:"libnetwork", WorkloadId:"libnetwork", EndpointId:"474957106ec3d6cffa3c0e4163595ded57dbbdb1144a67b97056e0065a82178d"} status="down"`

**Comment by CharlieR-o-o-t** [comment]
UPDATE: 
Guys, I'm sure that issue at the side of docker behavior. 

Docker 18.03
Calico node v2.6.8/v2.6.9
CentOS Linux release 7.4.1708

libnetwork: GET /IpamDriver.GetCapabilities
{"RequiresMACAddress":false}
 instructs docker do not change MAC address inside container. 

So at container inspect it's empty:
`"MacAddress": ""`

I see can see calico netplugin response with MAC provided, but seems that Docker ignores *MacAddress* field: 
`libnetwork-plugin[32378]:` time="2018-04-26T13:51:40Z" level=info msg="CreateEndpoint response" JSON="{"Interface":{"Address":"","AddressIPv6":"","MacAddress":"EE:EE:EE:EE:EE:EE"}}"``

**Comment by caseydavenport** [comment]
@CharlieR-o-o-t have you been able to confirm that setting that fixes the issue?

I'm a bit surprised since Calico doesn't rely on a specific MAC value being set.

> error=Link not found ifaceName="cali474957106ec" ipVersion=0x4 Apr 26 08:13:26 hostname calico-felix[20127]: 2018-04-26 08:13:26.162 [INFO][20127] route_table.go 293: Interface missing, will retry if it appears

This seems to indicate that the veth doesn't exist on the host at all. Do you see it in the output of `ip link show` on the host machine?

My guess is that there is another log with type `[ERROR]` earlier in the log which would show why the veth doesn't exist.

**Comment by vikaskedia** [comment]
Might be related to: https://github.com/projectcalico/calico/issues/1991

**Comment by CharlieR-o-o-t** [comment]
@caseydavenport , yes, this setting fixes issue, but I'm not sure that this is correct way to fix. 

This fix instructs docker to manage MAC, so mac address will be generated/configured by docker daemon. Before the fix there was mac management at the side of network plugin, mac was set to something like 'ee:ee:ee:ee:ee ... '

> Do you see it in the output of ip link show on the host machine?
Yes, it's exists.

**Comment by tmjd** [comment]
@CharlieR-o-o-t So with your change https://github.com/projectcalico/libnetwork-plugin/pull/178 what is the resulting MAC address of containers? Do they have "ee:ee:ee:ee:ee:ee" or a generated address?

Calico doesn't really care about the MAC address. The reason it is set to that value was because there were some rare cases where the kernel was having trouble generating a MAC address, so since it doesn't matter we just set it to a hard coded value to avoid those cases.

I wonder if there is a bug that if RequiresMACAddress is false (unset), that permission is not granted that  allows setting the MAC address.  I did find https://github.com/moby/moby/blob/6f68db8c7a94489b5e66bb828f748d0baa2e5c22/daemon/network.go#L706 but I'm not quite sure of the code flow and if that `c.Config.MacAddress` would be set.

**Comment by CharlieR-o-o-t** [comment]
@tmjd , yes, I understand approach. But calico will work only in case dockerd set sandbox Mac to "ee:ee:ee:ee:ee:ee". 

I spent time with debugging dockerd and can confirm that now dockerd daemon ignores response with Mac address from calico-libnetwork plugin. 

This was broken from version docker-ce 17.12, commit: 
https://github.com/docker/docker-ce/commit/eeeede3c5fb19289726b8b5a2481e17094302f48
MacAddress are not going to be written to endpoint key-value storage, so, it's simply lost. 
I need to verify some things, after that I'll prepare PR to moby to fix this.

**Comment by CharlieR-o-o-t** [comment]
Yes, bug at the interface Endpoint.Info, it's retrieve only incomplete data from KV storage (without calico-libnetwork MacAddress)
Created - https://github.com/docker/for-linux/issues/348

**Comment by CharlieR-o-o-t** [comment]
I have created PR : https://github.com/docker/libnetwork/pull/2205
awaiting merge.
