### ISSUE TITLE
`calicoctl version` should ouput CNI version as well

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calicoctl#1826]
Would be really useful for diagnostics if it tried to print out the CNI version if the plugin existed. 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* calicoctl version (e.g. `calicoctl version`):
* calico/node version (e.g. `docker run --rm calico/node versions`)
* Orchestrator type and version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

**Comment by dmmcquay** [comment]
To clarify a bit, the goal is to get the cni-plugin version (not spec version cni which https://github.com/projectcalico/libcalico-go/pull/877 does). 

There is some difficulty in deciding how to get the version of the cni-plugin into the datastore because there is no guarantee in how things will come up (etcd, calico/node startup, etc.).

**Comment by caseydavenport** [comment]
I'm going to close this as wontfix for now.
