### ISSUE TITLE
Possible to use calicoctl with typha?

### ISSUE THREAD

**Issue by standaloneSA** [projectcalico/calicoctl#2028]
There appears to be no support for [typha ](https://github.com/projectcalico/typha) in calicoctl
## Expected Behavior
Configuration directives for talking to typha

## Current Behavior
No configuration directives for talking to typha

## Possible Solution
Add configuration directives (and supporting code) for talking to typha

## Steps to Reproduce (for bugs)

1. Have typha
2. Try to configure calicoctl
3. Sadness

## Context
I'm using typha to scale out my calico nodes, and it was very successful in reducing load. Unfortunately, calicoctl expects an etcd endpoint, and I don't have one of these. Is there a plan for adding support? 

## Your Environment
30-node heavy churn CI/CD endpoint cluster. Bare metal, generic kubeadm-sourced kubernetes 1.13.3 cluster.

**Comment by lwr20** [comment]
I'm not sure I understand what the problem is here, but there appear to be a couple of false assumptions in the above.  I'll attempt to address them:
- `calicoctl` does not talk to calico components, it sets configuration values in the datastore, which calico components access to update their config as needed.  There is no need for it to "talk to typha".
- `calicoctl` (like other calico components) can talk to either etcd or kubernetes datastores - you need to configure it to talk to the same datastore your setup is using. See https://docs.projectcalico.org/v3.7/getting-started/calicoctl/install and https://docs.projectcalico.org/v3.7/getting-started/calicoctl/configure/
