### ISSUE TITLE
Looks like release v3.9.1 and v3.9.2 are the same

### ISSUE THREAD

**Issue by chenrui333** [projectcalico/calicoctl#2072]
Looks like the two release tags are tagging the same commit?

https://github.com/projectcalico/calicoctl/compare/v3.9.1...v3.9.2

Relates to https://github.com/Homebrew/homebrew-core/pull/45340

**Comment by caseydavenport** [comment]
@chenrui333 yeah, that's expected for patch releases where no changes have occurred.

It's a bit awkward - we version all of Calico as a single version so that it's easier for users to find components that are compatible with each other. That means if we fix a bug in one component, we re-release all the others as well, potentially at the same commit as the previous release.

**Comment by chenrui333** [comment]
Good to know. Thanks for the explanations!
