### ISSUE TITLE
Docker build is running off of older version of RHEL UBI

### ISSUE THREAD

**Issue by kelly-brown** [projectcalico/calicoctl#2460]
I'm seeing some security vulnerabilities cropping up in our scanning of the calioctl image out on docker hub.  Looks like you guys are tagging that to RHEL 8.2  I think 8.5 went GA on 11/9/2021.  Can you guys get an update in the queue?

Thanks!

https://access.redhat.com/articles/3078

**Comment by caseydavenport** [comment]
For what it is worth, the calicoctl image only uses UBI as an intermediate layer in order to add some license files to the produced image. There is no UBI code in the final resulting image, which is actually just scratch with the compiled binary and license file present: https://github.com/projectcalico/calicoctl/blob/master/Dockerfile.amd64#L20-L38

That said, should still be fine to bump the version, it's just not actually going to make a difference in the resulting image's security profile.

**Comment by Akasurde** [comment]
resolved_by_pr #2465
