### ISSUE TITLE
Feature Request: Add --verbose option to calicoctl

### ISSUE THREAD

**Issue by tomdee** [projectcalico/calicoctl#737]
This could provide extra insight into what calicoctl is doing and help diagnose issues that users are having.

It could print out the relevant parts of the environment to allow users to spot if they don't have things set up as they think they do (very common since we require sudo for some commands and not others).

**Comment by matthewdupre** [comment]
Best to have a specific list of information to do anything about this - it sounds like this is coming out of specific problems people have had.  What additional verbose output from what commands would have helped in each specific case?

**Comment by robbrockbank** [comment]
@tomdee Correct me if I'm wrong, but I think the idea here is really to indicate what calicoctl is doing under-the-covers, so in particular we'd be tracing out environment variables that are picked up and used, and indicating which calls we are invoking (e.g. when running netns commands, or equivalent Docker commands)

**Comment by tomdee** [comment]
Yes

**Comment by caseydavenport** [comment]
@robbrockbank doesn't the Go calicoctl support this? Or am I imagining things?

**Comment by robbrockbank** [comment]
@tomdee I'm not sure how relevant this is now:

-  We don't do any networking stuff within calicoctl anymore
-  We do print out the `docker run` command for `calicoctl node run`

I don't think any of the other commands do anything that the user would care about.  It is possible to turn on low level logging too if required (but that's not really what this issue was about).

WDYT?  Perhaps close?

**Comment by tomdee** [comment]
Yeah, I'm happy to close it.
