### ISSUE TITLE
Improve calico/node IP address detection

### ISSUE THREAD

**Issue by tomdee** [projectcalico/calicoctl#873]
Our current method fails in too many cases.

It is however a really useful feature - e.g. for deploying as a kubernetes daemonset

**Comment by wrouesnel** [comment]
A middleground option might be to allow specifying a DNS A/AAAA record which lists ALL public IP addresses a host could have. This would help resolve ambiguity, and in (at least my) deployment scenarios isn't too hard to setup in advance with shared images.

So `nodes.cloud.com` resolves to something like 192.168.1.10 and 192.168.1.11 - `calicoctl` retrieves all records, and checks all the interface IPs it has for one in the list.

**Comment by olavmrk** [comment]
I also just hit this problem -- calico-node picked the wrong address on a node with multiple interfaces.

A simple way to pick the source address may be to just create a UDP socket and connect it to a public address. Since this is a UDP socket, no packets will be sent, but Linux will still bind the socket to the local IP it would use for sending packets:

```
s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
s.connect( ('8.8.8.8', 0) )
default_src_ip = s.getsockname()[0]
```

**Comment by matthewdupre** [comment]
It would be helpful if we could get the specific failure cases: perhaps `ip addr` output, and an indication of what was picked, and what should have been picked.

**Comment by caseydavenport** [comment]
One case I've hit numerous times -

A vagrant setup with an eth0 which is NAT'd for internet access, and then an eth1 which is host-local and is meant for cluster traffic. All the eth0 interfaces have the same `10.0.2.15` address, and the eth1 interfaces have `172.18.18.X` addresses.

Calico always picks `10.0.2.15`.  For this, being able to specific which interface to pick an address from would probably be enough (this is also how flannel does it).

Without thinking __too_ much about it, this might work:
- An option to use a specific, exact IP address.
- An option limit chosen address to a specific interface (provided one exists on the node, error otherwise)
- An option limit chosen address from a specific CIDR (provided one exists on the node, error otherwise.)
- Default behavior of picking the first address on the first interface.

**Comment by caseydavenport** [comment]
Sticking this at P2 since I think people will start to feel the pain here with Kubernetes self-hosted.

**Comment by caseydavenport** [comment]
@tomdee @matthewdupre What do you think of the proposal in my comment above?

**Comment by dkoshkin** [comment]
I ran into a very similar scenario as your described @caseydavenport, in Vagrant there are 2 IPs in the `eth1` interface (one assigned via DHCP in Virtualbox) a wrong IP was chosen. What does the `--IP` option do in `calico node`, does that not specify the IP to use? Because it was using the wrong IP bird was failing to reach the other hosts.

**Comment by caseydavenport** [comment]
@dkoshkin Yes, the `--ip` option will specify the IP address to use.  There are a number of scenarios where it isn't easy to automate populating that field, so this issue is about making the auto-detection better to handle those cases.

**Comment by lwr20** [comment]
Autodetection is fraught with problems.  The only one who knows for sure is the human deploying.  

If specifying exactly is a pain for automation, can we specify the subnet that the correct address should come from?  Surely the user will know that?

**Comment by caseydavenport** [comment]
> If specifying exactly is a pain for automation, can we specify the subnet that the correct address should come from? Surely the user will know that?

@lwr20 See my proposal above :)

**Comment by matthewdupre** [comment]
I think allowing people to specify an interface name to pull the address from would be OK.  I don't like the CIDR restriction: I don't see a compelling use case for it where interface name wouldn't be suitable; and adding more options gratuitously is a bad thing.

**Comment by caseydavenport** [comment]
@matthewdupre the use-case is probably just "I have a bunch of machines with different interface names but they're all part of the same cluster".

I'm not sure how common that is, but would be happy to leave it off and see if it's needed down the road.  The design certainly allows for that to be added later :)

**Comment by lwr20** [comment]
I've been bitten by interface names before - ISTR that the naming of an interface can be dependant on the order in which interfaces are detected on boot.

**Comment by djosborne** [comment]
I want to propose something a bit different, hope this isn't too off topic.

`calicoctl node start --can-reach=10.0.0.1`. This would cause calico to bind to whichever IP is used to reach `--can-reach`:

```
s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
s.connect( (CAN_REACH_ADDR, 0) )
default_src_ip = s.getsockname()[0]
```

Users can set `--can-reach` to whatever makes most sense.
- The etcd address
- The "master" (depending on the orchestrator)
- `8.8.8.8`
- the nexthop of a private interface that all calico hosts are connected on.

We are already doing  this via a [plugin binary in calico-dcos](https://github.com/projectcalico/calico-dcos/blob/master/installer/installer.py#L456), it works fairly well.

**Comment by caseydavenport** [comment]
For my use-case, I'd be fine with a `CAN_REACH` env variable.

**Comment by caseydavenport** [comment]
I think this is a key feature we should be looking to address in v2.1.0.

CC @tomdee

**Comment by tomdee** [comment]
@robbrockbank Could you share your design for solving this (when you have it) so we can all discuss and comment 😄

**Comment by pmichali** [comment]
I hit this too, on a kubeadm host-based setup where I have multiple interfaces and a bond I/F is being used as the main interface and calico-node is selecting a different interface. One suggestion would be to make sure the logging indicates what interface was chosen - as I only found out at pod create time, when the local endpoint was using a different I/F.

**Comment by djosborne** [comment]
#1500 has been merged, which adds a new pluggable IP detection module. The old method is now referred to as "first-found". Additionally, a new "can-reach" method (using the initial design from the [above comment](https://github.com/projectcalico/calicoctl/issues/873#issuecomment-262063361)) 

Documentation on this new method is here: http://docs.projectcalico.org/master/reference/node/configuration#ip-autodetection-methods

Since this github issue has turned into mostly a design chat, I'm going to lock the issue. Please open new issues for further assistance.
