### ISSUE TITLE
data storage with consul

### ISSUE THREAD

**Issue by duffqiu** [projectcalico/calicoctl#941]
Is it possible to use consul instead of etc?

thanks

**Comment by fasaxc** [comment]
Not at this time.  We may add that feature in future but it's not a simple drop-in replacement (we've done a year of performance and scale testing with etcd that we'd have to repeat).

**Comment by tlvenn** [comment]
It would be pretty neat to do so. For people operating a consul cluster already, it's not really appealing to have to run an etcd cluster as well.

**Comment by fasaxc** [comment]
We're working on introducing an API around the datastore.  Once that work is complete, we'd welcome contributions to add additional datastores.

**Comment by tlvenn** [comment]
Hi @fasaxc , that's pretty good news ! Is there any estimate as when this API will surface ? Thanks !

**Comment by fasaxc** [comment]
@tlvenn The API is in libcalico-go: https://github.com/projectcalico/libcalico-go/blob/master/lib/backend/api/api.go, which will be used by Felix in due course.  Right now, there's only an etcdv2 implementation. In the etcd package.

If you're interested in contributing an alternative, you should come chat to us on the calicousers slack in the calico-dev channel.  While we've got an API, we don't yet have a way to select between different versions (because there's only one!) and implementing the API has some subtlety in the Syncer interface.

**Comment by tlvenn** [comment]
@fasaxc wouldnt it be simpler to integrate https://github.com/docker/libkv ? So that all backends such as etcd, consul, zookeeper are already handled ?

**Comment by fasaxc** [comment]
@tlvenn I don't think libkv provides what we need for Calico right now.  We'd need a GetTree operation and a version of WatchTree that supported consistency guarantees vs the values returned from GetTree.

We also have in mind to support non-KV-based datastores behind our API, which is why our API is one layer of abstraction above libkv (it uses typed structs for its keys and values).

We'd welcome a libkv backend for the API but adding the required features to libkv is non-trivial.  I think it'd be doable for etcd and consul but I don't think Zookeeper has the required features to support consistent GetTree and WatchTree.

**Comment by tlvenn** [comment]
Thanks for the clarification @fasaxc , I guess it was worth to check ;)

**Comment by caseydavenport** [comment]
A PR for this is in the works over here: https://github.com/projectcalico/libcalico-go/pull/319

**Comment by fasaxc** [comment]
Assigning to @robbrockbank since I think he's got the associated PR.

**Comment by Eywek** [comment]
Any updates on this?

**Comment by caseydavenport** [comment]
@Eywek there isn't any work on this as far as I know.

Since the original request, I no longer think this is something that the core Calico team wants to support since it takes quite a bit of effort to maintain feature compatibility and testing required to call a datastore backend supported.

Using the Kubernetes API backend should solve the original issue, since it doesn't require a separate etcd cluster for Calico.
